### ISSUE TITLE
Matplotlib is Heavy Load for a Simple Function

### ISSUE THREAD

**Issue by alanderex** [FlorianWilhelm/pytanis#20]
### `matplotlib` is a huge dependency and still may cause trouble on macOS-arm64

`matplotlib` is a dependency and only used to convert color names to RBG tuples.

```python
def mark_rows(worksheet, mask: pd.Series, color: ColorType):
    ...
    fmt = cellFormat(backgroundColor=Color(*to_rgb(color)))
```

👉 Installing matplotlib can still be tricky on macOS-arm64 due and fail.
👉 Having a huge package as `matplotlib`as a dependency just to convert color names to RBG tuples is a bad idea. 

### Proposed Solution: webcolors

[webcolors](https://github.com/ubernostrum/webcolors) is a lightweight library offering conversion of color names to RBG tuples

```python
def mark_rows(worksheet, mask: pd.Series, color: ColorType):
    ...
    color_rgb = name_to_rgb(color)if isinstance(color, str) else color[:3]
    fmt = cellFormat(backgroundColor=Color(*color_rgb))
```

remove `matplotlib` from dependencies (it's still used via seaborn in optional dependencies)

## Versions and main components

* Pytanis Version: 0.7.1
* Python Version: 3.12
* Operating system: macOS 14.1

**Comment by FlorianWilhelm** [comment]
Really good point! Thanks @alanderex for directly providing a PR :-)
